// Code generated by mockery v1.0.0. DO NOT EDIT.

package iohelper

import mock "github.com/stretchr/testify/mock"

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: path, data
func (_m *MockWriter) Write(path string, data []byte) error {
	ret := _m.Called(path, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(path, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
