// Code generated by gokit v0.0.1. DO NOT EDIT.

package service

import (
	"context"

	"github.com/bongnv/gokit/examples/hello"
	"github.com/go-kit/kit/endpoint"
)

// endpoints ...
type endpoints struct {
	HelloEndpoint endpoint.Endpoint
	ByeEndpoint   endpoint.Endpoint
}

// makeEndpoints returns an Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func makeEndpoints(s hello.Service) endpoints {
	return endpoints{
		HelloEndpoint: makeHelloEndpoint(s),
		ByeEndpoint:   makeByeEndpoint(s),
	}
}

// makeEndpoint returns an endpoint via the passed service.
func makeHelloEndpoint(s hello.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {

		req := request.(*hello.Request)
		resp, e := s.Hello(ctx, req)
		return resp, e

	}
}

// makeEndpoint returns an endpoint via the passed service.
func makeByeEndpoint(s hello.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {

		req := request.(*hello.ByeRequest)
		resp, e := s.Bye(ctx, req)
		return resp, e

	}
}
