// Code generated by gokit v0.0.1. DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/bongnv/gokit/examples/hello"
	"github.com/bongnv/gokit/util/server"
)

// GetOptions ...
func GetOptions(s hello.Service) []server.Option {
	serverEndpoints := makeEndpoints(s)

	opts := []server.Option{}

	opts = append(opts, getHTTPOptions(serverEndpoints)...)

	return opts
}

func getHTTPOptions(serverEndpoints endpoints) []server.Option {
	opts := []server.Option{}

	opts = append(opts,
		server.WithHTTPEndpoint(server.Endpoint{
			Method:         "",
			Path:           "/hello",
			Endpoint:       serverEndpoints.HelloEndpoint,
			RequestDecoder: decodeServiceHelloRequest,
		}),
		server.WithHTTPEndpoint(server.Endpoint{
			Method:         "",
			Path:           "/bye",
			Endpoint:       serverEndpoints.ByeEndpoint,
			RequestDecoder: decodeServiceByeRequest,
		}),
	)

	return opts
}

func decodeServiceHelloRequest(_ context.Context, r *http.Request) (request interface{}, err error) {
	var req *hello.Request
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return nil, err
	}

	return req, err
}

func decodeServiceByeRequest(_ context.Context, r *http.Request) (request interface{}, err error) {
	var req *hello.ByeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return nil, err
	}

	return req, err
}
