// Code generated by mockery v1.0.0. DO NOT EDIT.

package parser

import mock "github.com/stretchr/testify/mock"

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: path, serviceName
func (_m *MockParser) Parse(path string, serviceName string) (*Data, error) {
	ret := _m.Called(path, serviceName)

	var r0 *Data
	if rf, ok := ret.Get(0).(func(string, string) *Data); ok {
		r0 = rf(path, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
