package generator

import (
	"bytes"
	"fmt"
	"log"
	"path/filepath"
	"text/template"

	"github.com/bongnv/gokit/internal/parser"
	"github.com/bongnv/gokit/internal/templates"
	"github.com/bongnv/gokit/internal/writer"
	"golang.org/x/tools/imports"
)

// Generator renders a template to a output.
type Generator struct {
	FilePath               string
	TemplateName           string
	Service                *parser.Service
	Writer                 writer.Writer
	WithAutogeneratedNotes bool
}

// Do generates a file given a template. Then, it uses writer to render output.
func (g *Generator) Do() error {
	buf, err := g.renderFromTemplate()
	if err != nil {
		return err
	}

	log.Println("Formatting ", filepath.Base(g.FilePath))
	formatedBuf, err := imports.Process(g.FilePath, buf, nil)
	if err != nil {
		fmt.Println("Failed to format. Content:", string(buf))
		return err
	}

	return g.Writer.Write(g.FilePath, formatedBuf)
}

func (g *Generator) renderFromTemplate() ([]byte, error) {
	log.Printf("Rendering from template %s..\n", g.TemplateName)

	templatePath := fmt.Sprintf("tmpl/%s.tmpl", g.TemplateName)
	tmplContent, err := templates.Asset(templatePath)
	if err != nil {
		return nil, err
	}

	codeTmpl, err := template.New("default").
		Funcs(getFuncMap()).
		Parse(string(tmplContent))

	if err != nil {
		return nil, err
	}

	buf := &bytes.Buffer{}
	if g.WithAutogeneratedNotes {
		buf.Write([]byte("// Code generated by gokit v0.0.1. DO NOT EDIT.\n\n"))
	}
	if err := codeTmpl.Execute(buf, g.Service); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
