name: Go
on: [push]
jobs:  
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.11, 1.12, 1.13]

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: CI
      run: make ci

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.11, 1.12, 1.13]

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
